# permissions for end users to view cosmosfullnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosmosfullnode-viewer-role
rules:
- apiGroups:
  - cosmos.altuslabsxyz.io
  resources:
  - cosmosfullnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cosmos.altuslabsxyz.io
  resources:
  - cosmosfullnodes/status
  verbs:
  - get
